const LOGO='https://raw.githubusercontent.com/oun-a/alola-4/main/public/alola-logo.jpg';
const QR='data:image/png;base64,'+(window.__ALOLA_QR||'');
const KEY='alola_voice_complete_v1';
let db;try{db=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){db=null}
if(!db)db={owners:[],properties:[],units:[],tenants:[],leases:[],dues:[],receipts:[],expenses:[],ownerTransfers:[],officeEntries:[],settings:{officeOpeningBalance:0}};
for(const k of ['owners','properties','units','tenants','leases','dues','receipts','expenses','ownerTransfers','officeEntries']) if(!Array.isArray(db[k])) db[k]=[];
if(!db.settings)db.settings={officeOpeningBalance:0};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m])),money=n=>Number(n||0).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2})+' ر.س',today=()=>new Date().toISOString().slice(0,10),uid=p=>p+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
const get=(t,id)=>db[t].find(x=>x.id===id),ownerName=id=>get('owners',id)?.name||'—',propertyName=id=>get('properties',id)?.name||'—',unitName=id=>get('units',id)?.name||'—',tenantName=id=>get('tenants',id)?.name||'—';
const nav=[['dashboard','🏠 الرئيسية'],['owners','👤 الملاك'],['properties','🏢 العقارات'],['units','🚪 الوحدات'],['tenants','👥 المستأجرون'],['leases','📄 العقود'],['dues','📅 الاستحقاقات'],['receipts','🧾 سندات القبض'],['expenses','💸 سندات الصرف'],['liabilities','💰 الذمم المالية'],['reports','📊 التقارير']];
$('nav').innerHTML=nav.map(n=>`<button data-p="${n[0]}">${n[1]}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.p));
function show(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active','printing'));$(p).classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.p===p));render(p);window.scrollTo(0,0)}
function render(p){({dashboard:renderDashboard,owners:renderOwners,properties:renderProperties,units:renderUnits,tenants:renderTenants,leases:renderLeases,dues:renderDues,receipts:renderReceipts,expenses:renderExpenses,liabilities:renderLiabilities,reports:renderReports}[p]||(()=>{}))()}
function currentPage(){return document.querySelector('.page.active')?.id||'dashboard'}
function del(type,id){if(confirm('هل أنت متأكد من الحذف؟')){db[type]=db[type].filter(x=>x.id!==id);save();render(currentPage())}}
function nextNo(prefix,arr){let mx=arr.reduce((m,x)=>Math.max(m,Number(String(x.no||'').split('-').pop())||0),0);return prefix+'-'+String(mx+1).padStart(5,'0')}
function formPage(section,title,body,onSubmit,afterRender){$(section).innerHTML=`<div class="top"><div><h1>${title}</h1><div class="muted">صفحة كاملة قابلة للتمرير والتعديل</div></div><button class="btn light" type="button" onclick="show('${section}')">رجوع</button></div><div class="card"><form id="editor">${body}<div class="actions" style="margin-top:18px"><button class="btn gold">حفظ</button><button type="button" class="btn light" onclick="show('${section}')">إلغاء</button></div></form></div>`;$('editor').onsubmit=async e=>{e.preventDefault();try{await onSubmit(Object.fromEntries(new FormData(e.target)),e.target);save();show(section)}catch(err){console.error(err)}};if(afterRender)afterRender()}
function monthsBetween(start,end,step){let a=[],d=new Date(start+'T00:00:00'),e=new Date(end+'T00:00:00');while(d<=e){a.push(d.toISOString().slice(0,10));d.setMonth(d.getMonth()+step)}return a}
function frequencyMonths(f){return {'شهري':1,'ربع سنوي':3,'نصف سنوي':6,'سنوي':12}[f]||1}
function duePaid(dueId){return db.receipts.filter(r=>r.dueId===dueId).reduce((a,r)=>a+Number(r.amount||0),0)}
function dueStatus(d){let p=duePaid(d.id),rem=Number(d.amount)-p;if(rem<=0)return 'مدفوع';if(p>0)return 'مدفوع جزئياً';if(d.dueDate<today())return 'متأخر';return 'مستحق'}
function dueBadge(s){return `<span class="badge ${s==='مدفوع'?'ok':s==='متأخر'?'bad':s==='مدفوع جزئياً'?'warn':''}">${s}</span>`}
function activeLeaseForTenant(tid){return db.leases.find(l=>l.tenantId===tid&&l.status==='نشط')}
function activeLeaseForUnit(uid){return db.leases.find(l=>l.unitId===uid&&l.status==='نشط')}
function ownerFigures(ownerId,month='',propertyId='',unitId=''){let rs=db.receipts.filter(r=>r.ownerId===ownerId&&(!month||String(r.date).startsWith(month))&&(!propertyId||r.propertyId===propertyId)&&(!unitId||r.unitId===unitId)),es=db.expenses.filter(e=>e.ownerId===ownerId&&(!month||String(e.date).startsWith(month))&&(!propertyId||e.propertyId===propertyId)&&(!unitId||e.unitId===unitId)),ts=db.ownerTransfers.filter(t=>t.ownerId===ownerId&&(!month||String(t.date).startsWith(month))&&(!propertyId&&!unitId));let o=get('owners',ownerId)||{};return{receipts:rs,expenses:es,transfers:ts,income:rs.reduce((a,x)=>a+Number(x.amount||0),0),expense:es.reduce((a,x)=>a+Number(x.amount||0),0),transferred:ts.reduce((a,x)=>a+Number(x.amount||0),0),opening:Number(o.openingLiability||0)}}
function ownerLiability(ownerId){let f=ownerFigures(ownerId);return f.opening+f.income-f.expense-f.transferred}
function officeFigures(){let receiptCash=db.receipts.reduce((a,x)=>a+Number(x.amount||0),0),propertyExpense=db.expenses.reduce((a,x)=>a+Number(x.amount||0),0),ownerTransfers=db.ownerTransfers.reduce((a,x)=>a+Number(x.amount||0),0),officeIncome=db.officeEntries.filter(x=>x.type==='دخل').reduce((a,x)=>a+Number(x.amount||0),0),officeExpense=db.officeEntries.filter(x=>x.type==='مصروف').reduce((a,x)=>a+Number(x.amount||0),0),opening=Number(db.settings.officeOpeningBalance||0);return{receiptCash,propertyExpense,ownerTransfers,officeIncome,officeExpense,opening,closing:opening+receiptCash-propertyExpense-ownerTransfers+officeIncome-officeExpense}}
function renderDashboard(){let of=officeFigures(),occupied=db.units.filter(u=>activeLeaseForUnit(u.id)).length,outstanding=db.dues.filter(d=>d.dueDate<=today()).reduce((a,d)=>a+Math.max(0,Number(d.amount)-duePaid(d.id)),0);$('dashboard').innerHTML=`<div class="top"><div><h1>لوحة التحكم</h1><div class="muted">الأولى لإدارة الأملاك</div></div><div class="actions"><button class="btn gold" onclick="receiptForm()">+ سند قبض</button><button class="btn" onclick="expenseForm()">+ سند صرف</button></div></div><div class="cards"><div class="card"><div class="kpi-label">العقارات</div><div class="num">${db.properties.length}</div></div><div class="card"><div class="kpi-label">الوحدات المؤجرة</div><div class="num">${occupied}/${db.units.length}</div></div><div class="card"><div class="kpi-label">المستحقات غير المسددة</div><div class="num">${money(outstanding)}</div></div><div class="card"><div class="kpi-label">رصيد المكتب النقدي</div><div class="num">${money(of.closing)}</div></div></div><div class="profile"><div class="card"><h3>ذمم الملاك الحالية</h3>${db.owners.map(o=>`<div class="linkcard"><b>${esc(o.name)}</b><div class="num" style="font-size:18px">${money(ownerLiability(o.id))}</div></div>`).join('')||'<div class="empty">لا يوجد ملاك</div>'}</div><div class="card"><h3>ملخص المكتب</h3><p>نقد داخل من سندات القبض: <b>${money(of.receiptCash)}</b></p><p>مصروفات عقارات: <b>${money(of.propertyExpense)}</b></p><p>تحويلات للملاك: <b>${money(of.ownerTransfers)}</b></p><p>دخل المكتب: <b>${money(of.officeIncome)}</b></p><p>مصروف المكتب: <b>${money(of.officeExpense)}</b></p></div></div>`}
function renderOwners(){let rows=db.owners.map(o=>{let f=ownerFigures(o.id);return `<tr><td><button class="btn light" onclick="ownerProfile('${o.id}')">${esc(o.name)}</button></td><td>${db.properties.filter(p=>p.ownerId===o.id).length}</td><td>${money(f.income)}</td><td>${money(f.expense)}</td><td>${money(f.transferred)}</td><td><b>${money(ownerLiability(o.id))}</b></td><td class="actions"><button class="btn light" onclick="ownerForm('${o.id}')">تعديل</button><button class="btn danger" onclick="del('owners','${o.id}')">حذف</button></td></tr>`}).join('');$('owners').innerHTML=`<div class="top"><div><h1>الملاك</h1><div class="muted">ملف ومحفظة وذمة مالية لكل مالك</div></div><button class="btn gold" onclick="ownerForm()">+ إضافة مالك</button></div><div class="card tablewrap">${rows?`<table class="table"><tr><th>المالك</th><th>العقارات</th><th>القبض</th><th>الصرف</th><th>المحول</th><th>الذمة الحالية</th><th>إجراءات</th></tr>${rows}</table>`:'<div class="empty">لا يوجد ملاك</div>'}</div>`}
function ownerForm(id=''){let o=get('owners',id)||{};formPage('owners',id?'تعديل المالك':'إضافة مالك',`<div class="formgrid"><div><label>اسم المالك</label><input name="name" required value="${esc(o.name)}"></div><div><label>الهوية / السجل</label><input name="idNo" value="${esc(o.idNo)}"></div><div><label>الجوال</label><input name="phone" value="${esc(o.phone)}"></div><div><label>البريد</label><input name="email" value="${esc(o.email)}"></div><div><label>البنك</label><input name="bank" value="${esc(o.bank)}"></div><div><label>IBAN</label><input name="iban" value="${esc(o.iban)}"></div><div><label>رصيد الذمة الافتتاحي</label><input type="number" name="openingLiability" value="${Number(o.openingLiability||0)}"></div><div class="full"><label>ملاحظات</label><textarea name="notes">${esc(o.notes)}</textarea></div></div>`,x=>{x.openingLiability=Number(x.openingLiability||0);id?Object.assign(o,x):db.owners.push({...x,id:uid('OWN')})})}
function ownerProfile(id){let o=get('owners',id),ps=db.properties.filter(p=>p.ownerId===id),f=ownerFigures(id);$('owners').innerHTML=`<div class="top"><div><h1>${esc(o.name)}</h1><div class="muted">ملف المالك ومحفظته</div></div><div class="actions"><button class="btn gold" onclick="ownerTransferForm('${id}')">+ تسجيل تحويل للمالك</button><button class="btn light" onclick="ownerForm('${id}')">تعديل</button><button class="btn light" onclick="show('owners')">رجوع</button></div></div><div class="cards"><div class="card">العقارات<div class="num">${ps.length}</div></div><div class="card">القبض<div class="num">${money(f.income)}</div></div><div class="card">الصرف<div class="num">${money(f.expense)}</div></div><div class="card">الذمة الحالية<div class="num">${money(ownerLiability(id))}</div></div></div><div class="profile"><div class="card"><h3>بيانات المالك</h3><p>الجوال: ${esc(o.phone)}</p><p>البنك: ${esc(o.bank)}</p><p>IBAN: ${esc(o.iban)}</p></div><div class="card"><h3>العقارات</h3>${ps.map(p=>`<div class="linkcard"><b>${esc(p.name)}</b><div class="muted">${esc(p.type)} — ${db.units.filter(u=>u.propertyId===p.id).length} وحدة</div></div>`).join('')||'—'}</div><div class="card wide"><h3>الحركة المالية</h3>${ownerTransactionTable(id)}</div></div>`}
function renderProperties(){let rows=db.properties.map(p=>`<tr><td><button class="btn light" onclick="propertyProfile('${p.id}')">${esc(p.name)}</button></td><td>${esc(p.type)}</td><td>${esc(ownerName(p.ownerId))}</td><td>${db.units.filter(u=>u.propertyId===p.id).length}</td><td>${esc(p.status||'نشط')}</td><td class="actions"><button class="btn light" onclick="propertyForm('${p.id}')">تعديل</button><button class="btn danger" onclick="del('properties','${p.id}')">حذف</button></td></tr>`).join('');$('properties').innerHTML=`<div class="top"><div><h1>العقارات</h1><div class="muted">العقار حاوية والوحدة هي المساحة المؤجرة فعلياً</div></div><button class="btn gold" onclick="propertyForm()">+ إضافة عقار</button></div><div class="card tablewrap">${rows?`<table class="table"><tr><th>العقار</th><th>النوع</th><th>المالك</th><th>الوحدات</th><th>الحالة</th><th>إجراءات</th></tr>${rows}</table>`:'<div class="empty">لا توجد عقارات</div>'}</div>`}
