// ALOLA premium presentation, print, backup, audit and integrity layer.
if(!Array.isArray(db.auditLog))db.auditLog=[];
function audit(action,entity,detail=''){db.auditLog.unshift({id:uid('AUD'),at:new Date().toISOString(),action,entity,detail});if(db.auditLog.length>500)db.auditLog=db.auditLog.slice(0,500)}
function deleteBlockReason(type,id){const checks={owners:[['properties','ownerId','عقارات'],['receipts','ownerId','سندات قبض'],['expenses','ownerId','سندات صرف'],['ownerTransfers','ownerId','تحويلات للمالك']],properties:[['units','propertyId','وحدات'],['receipts','propertyId','سندات قبض'],['expenses','propertyId','سندات صرف']],units:[['leases','unitId','عقود'],['receipts','unitId','سندات قبض'],['expenses','unitId','سندات صرف']],tenants:[['leases','tenantId','عقود'],['receipts','tenantId','سندات قبض']],leases:[['dues','leaseId','استحقاقات'],['receipts','leaseId','سندات قبض']],dues:[['receipts','dueId','مدفوعات مرتبطة']]};for(const [t,f,label] of(checks[type]||[]))if(db[t]?.some(x=>x[f]===id))return `لا يمكن الحذف: يوجد ${label} مرتبطة بهذا السجل. عدّل أو أنهِ الارتباط أولاً.`;return''}
const _saveBase=save;save=function(){_saveBase()};
del=function(type,id){const reason=deleteBlockReason(type,id);if(reason){alert(reason);return}if(confirm('هل أنت متأكد من الحذف؟')){const item=get(type,id);audit('حذف',type,item?.name||item?.no||id);db[type]=db[type].filter(x=>x.id!==id);save();render(currentPage())}};
const _formPageBase=formPage;formPage=function(section,title,body,onSubmit,afterRender){_formPageBase(section,title,body,async(data,form)=>{await onSubmit(data,form);audit('حفظ/تعديل',section,title)},afterRender)};
function exportBackup(){const payload={version:2,exportedAt:new Date().toISOString(),data:db};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='ALOLA-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);audit('نسخة احتياطية','system','تصدير JSON');save()}
function importBackupFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result),data=parsed.data||parsed;if(!data||!Array.isArray(data.owners)||!Array.isArray(data.properties))throw new Error('invalid');if(!confirm('سيتم استبدال بيانات هذا المتصفح بالنسخة المختارة. هل تريد المتابعة؟'))return;db=data;for(const k of['owners','properties','units','tenants','leases','dues','receipts','expenses','ownerTransfers','officeEntries','auditLog'])if(!Array.isArray(db[k]))db[k]=[];if(!db.settings)db.settings={officeOpeningBalance:0};audit('استعادة نسخة','system',file.name);save();alert('تمت استعادة النسخة الاحتياطية بنجاح');show('dashboard')}catch(e){alert('ملف النسخة الاحتياطية غير صالح')}};r.readAsText(file)}
function renderSettings(){const rows=db.auditLog.slice(0,80).map(a=>`<tr><td>${new Date(a.at).toLocaleString('ar-SA')}</td><td>${esc(a.action)}</td><td>${esc(a.entity)}</td><td>${esc(a.detail)}</td></tr>`).join('');$('settings').innerHTML=`<div class="top"><div><h1>الإعدادات والحوكمة</h1><div class="muted">نسخ احتياطي، استعادة، وسجل تغييرات</div></div></div><div class="profile"><div class="card"><h3>النسخ الاحتياطي</h3><p class="muted">نزّل نسخة كاملة من بيانات النظام واحفظها خارج المتصفح.</p><div class="actions"><button class="btn gold" onclick="exportBackup()">تنزيل نسخة احتياطية الآن</button><label class="btn light file-label">استعادة نسخة<input type="file" accept=".json,application/json" onchange="importBackupFile(this.files[0])"></label></div></div><div class="card"><h3>جاهزية الإنتاج</h3><p><b>الوضع الحالي:</b> تخزين محلي داخل المتصفح.</p><p class="muted">الواجهة والعمليات جاهزة، لكن الاستخدام متعدد الأجهزة والمستخدمين يحتاج قاعدة بيانات سحابية ومصادقة وتخزين ملفات سحابي.</p></div><div class="card wide"><h3>سجل التغييرات</h3><div class="tablewrap">${rows?`<table class="table"><tr><th>الوقت</th><th>الإجراء</th><th>القسم</th><th>التفصيل</th></tr>${rows}</table>`:'<div class="empty">لا توجد عمليات مسجلة بعد</div>'}</div></div></div>`}
if(!nav.some(x=>x[0]==='settings'))nav.push(['settings','⚙ الإعدادات']);$('nav').innerHTML=nav.map(n=>`<button data-p="${n[0]}">${n[1]}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.p));
render=function(p){({dashboard:renderDashboard,owners:renderOwners,properties:renderProperties,units:renderUnits,tenants:renderTenants,leases:renderLeases,dues:renderDues,receipts:renderReceipts,expenses:renderExpenses,liabilities:renderLiabilities,reports:renderReports,settings:renderSettings}[p]||(()=>{}))()};
function premiumDocFooter(){return `<div class="doc-footer"><div class="doc-company"><b>الأولى لإدارة الأملاك</b><span>وثيقة مالية صادرة إلكترونياً من النظام</span><div class="signature-grid"><div>توقيع المستلم</div><div>اعتماد الإدارة</div></div></div><div class="qr-wrap"><img class="qr" src="${QR}"><span>امسح رمز QR لبيانات التواصل الرسمية</span></div></div>`}
openReceipt=function(id){const r=get('receipts',id),lease=get('leases',r.leaseId);$('document').innerHTML=`<div class="top screen-only"><h1>${esc(r.no)}</h1><div class="actions"><button class="btn gold" onclick="printDocument()">طباعة / PDF</button><button class="btn light" onclick="show('receipts')">رجوع</button></div></div><div class="doc"><div class="dochead"><img class="logo" src="${LOGO}"><div class="doctitle"><div class="doc-kicker">ALOLA PROPERTY MANAGEMENT</div><h2>سند قبض</h2><b>الأولى لإدارة الأملاك</b><div class="doc-number">رقم السند: ${esc(r.no)}</div></div></div><div class="docmeta"><span>تاريخ الإصدار: ${esc(r.date)}</span><span>مرجع داخلي: ${esc(r.id)}</span></div><table><tr><th>طريقة الدفع</th><td>${esc(r.method)}</td><th>المستأجر</th><td>${esc(tenantName(r.tenantId))}</td></tr><tr><th>المالك</th><td>${esc(ownerName(r.ownerId))}</td><th>العقار</th><td>${esc(propertyName(r.propertyId))}</td></tr><tr><th>الوحدة</th><td>${esc(unitName(r.unitId))}</td><th>العقد</th><td>${esc(lease?.contractNo||'—')}</td></tr><tr class="amount-row"><th>المبلغ المستلم</th><td colspan="3"><b>${money(r.amount)}</b></td></tr><tr><th>البيان</th><td colspan="3">${esc(r.description)}</td></tr></table>${premiumDocFooter()}</div>`;show('document')};
openExpense=function(id){const e=get('expenses',id);$('document').innerHTML=`<div class="top screen-only"><h1>${esc(e.no)}</h1><div class="actions"><button class="btn gold" onclick="printDocument()">طباعة / PDF</button><button class="btn light" onclick="show('expenses')">رجوع</button></div></div><div class="doc"><div class="dochead"><img class="logo" src="${LOGO}"><div class="doctitle"><div class="doc-kicker">ALOLA PROPERTY MANAGEMENT</div><h2>سند صرف</h2><b>الأولى لإدارة الأملاك</b><div class="doc-number">رقم السند: ${esc(e.no)}</div></div></div><div class="docmeta"><span>تاريخ الإصدار: ${esc(e.date)}</span><span>مرجع داخلي: ${esc(e.id)}</span></div><table><tr><th>طريقة الدفع</th><td>${esc(e.method)}</td><th>المالك</th><td>${esc(ownerName(e.ownerId))}</td></tr><tr><th>العقار</th><td>${esc(propertyName(e.propertyId))}</td><th>الوحدة</th><td>${esc(unitName(e.unitId))}</td></tr><tr><th>الفئة</th><td>${esc(e.category)}</td><th>الفاتورة</th><td>${e.attachment?.name?esc(e.attachment.name):'لا يوجد'}</td></tr><tr class="amount-row"><th>المبلغ المصروف</th><td colspan="3"><b>${money(e.amount)}</b></td></tr><tr><th>البيان</th><td colspan="3">${esc(e.description)}</td></tr></table>${premiumDocFooter()}</div>`;show('document')};
